#instal: https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###
GET http://localhost:8080/routes

###
GET http://localhost:8080/routes/5dd90fd3dff57531549c5279

###
DELETE  http://localhost:8080/routes/5ddeead6a994b10b10a5075a

###
PUT http://localhost:8080/routes/5ddeead6a994b10b10a5075a
Content-Type: application/json

{
    "name": "2koty 333"
}

###
POST http://localhost:8080/routes
Content-Type: application/json

{
    "name":"kot",
    "startDate":1573100105,
    "endDate":1573119105,
    "coords":
        [
            {
                "latitude":57.55555,
                "longitude":-15.888,
                "altitude":25,
                "timestamp":1573119105
            },
            {
                "latitude":57.55555,
                "longitude":-15.888,
                "altitude":25,
                "timestamp":1573119105
            },
            {
                "latitude":57.55555,
                "longitude":-15.888,
                "altitude":25,
                "timestamp":1573119105
            },
                {
                "latitude":57.55555,
                "longitude":-15.888,
                "altitude":25,
                "timestamp":1573119105
            },
                {
                "latitude":57.55555,
                "longitude":-15.888,
                "altitude":25,
                "timestamp":1573119105
            }
        ]
}



###
POST http://localhost:8080/routes/comment/5ddeead6a994b10b10a5075a

Content-Type: application/json

{
    "name":"Post",
    "startDate":1573100105,
    "endDate":1573119105,
    "coords":
        [
            {
                "latitude":57.55555,
                "longitude":-15.888,
                "altitude":25,
                "timestamp":1573119105
            }
        ]
}







