#instal: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

GET http://localhost:8080/sub

###

GET http://localhost:8080/sub/5dc335364cf92a252c742264

###

POST http://localhost:8080/sub
Content-Type: application/json

{
    "name": "Post",
    "subToChanel": "test2"
}

### 
DELETE  http://localhost:8080/sub/5dc335364cf92a252c742264


###

PUT http://localhost:8080/sub/5dc328bba1e37939546ecda3
Content-Type: application/json

{
    "name": "PUT",
    "subToChanel": "PUT"
}

###


# PATCH http://localhost:8080/sub/5dc328bba1e37939546ecda3
# Content-Type: application/json

# {
#     "name": "PATCH",
#     "subToChanel": "PATCH"
# }




